---
title: "ESM 244 Lab Week 2"
author: "Lucas Empson"
date: "1/18/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(janitor)
library(palmerpenguins)
library(here)

# For PCA:
library(ggfortify)
# For ggplot customization:
library(readxl)
library(gghighlight)
library(lubridate)
library(plotly)
# To make compound figures:
library(patchwork)
```

### Part 1: PCA with penguins

```{r}
penguin_pca <- penguins %>% 
  select(body_mass_g, ends_with("_mm")) %>% 
  drop_na() %>% 
  scale() %>% 
  prcomp()

penguin_pca$rotation

penguin_complete <- penguins %>% 
  drop_na(body_mass_g, ends_with("_mm"))

autoplot(penguin_pca,
         data = penguin_complete,
         colour = 'species',
         loadings = TRUE,
         loadings.label = TRUE) +
  theme_minimal()
```

### Part 2: ggplot2 customization & reading in different file types

#### Read in an .xlsx file

```{r}
fish_noaa <- read_excel(here("data", "foss_landings.xlsx")) %>% 
  clean_names() %>% 
  mutate(across(where(is.character), tolower)) %>% 
  mutate(nmfs_name = str_sub(nmfs_name, end = -4)) %>% 
  filter(confidentiality == "public")
```

Make a customized graph:
```{r}
fish_plot <- ggplot(data = fish_noaa, aes(x = year, y = pounds)) +
  geom_line(aes(color = nmfs_name), show.legend = FALSE) +
  theme_minimal()

fish_plot

ggplotly(fish_plot)

### Use gghighlight to highlight certain series

ggplot(data = fish_noaa, aes(x = year, y = pounds, group = nmfs_name)) +
  geom_line(aes(color = nmfs_name)) +
  theme_minimal() +
  gghighlight(max(pounds) > 1e8)

```



